model_reasoning_effort = "xhigh"
personality = "pragmatic"
model = "gpt-5.3-codex"

notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

[features]
web_search_request = true

[mcp_servers]

[projects."/Users/chiyuu/Documents/git/PraLoop"]
trust_level = "trusted"
